### ISSUE TITLE
关于label_idx.txt的问题

### ISSUE THREAD

**Issue by Z-Lee-corder** [xmuqimingxia/HINTED#1]
作者您好，有两个问题想请教您：
我注意到这个代码是基于HSSDA开发的，论文中您提出的方法是在1%与2%的训练集标签数据下训练验证的。而在您提供的label_idx.txt文件中，却包含了10%的训练集标签数据。如果想要复现您的方法，应该要重新生成1%和2%标签量下的一些数据集文件吧，如label_idx.txt，kitti_infos_train.pkl, kitti_dbinfos_train.pkl, gt_database等文件吧。

另外这个包含了10%的标签数据的label_idx.txt文件是如何生成的呢。我发现HSSDA代码中是通过python split.py实现的标签分割。那么您能像HSSDA那样，提供一下生成这个10%的label_idx的txt文件呢（如train_0.1_1.txt, train_0.1_2.txt, train_0.1_3.txt,）

**Comment by xmuqimingxia** [comment]
谢谢您的Issue。实际上我们是稀疏监督的设置，与半监督设置下的HSSDA不同，我们对于label_idx.txt中的训练数据，每一帧只保留一个实例的标注。实际的标注代价为就是2% （10% * 20%）。对应的kitti_infos_train.pkl我们在项目中给出了。kitti_dbinfos_train.pkl, gt_database直接按照现有代码生成即可。

**Comment by xmuqimingxia** [comment]
补充说明：在稀疏监督的早期论文中有如下阐述：对于KITTI数据集，每一场景只标注一个实例，最后占用的标注代价是全监督代价的20%。所以我们只对10%的训练集保留一个实例，则标注代价为：10% * 20% = 2%。

**Comment by Z-Lee-corder** [comment]
> 谢谢您的Issue。实际上我们是稀疏监督的设置，与半监督设置下的HSSDA不同，我们对于label_idx.txt中的训练数据，每一帧只保留一个实例的标注。实际的标注代价为就是2% （10% * 20%）。对应的kitti_infos_train.pkl我们在项目中给出了。kitti_dbinfos_train.pkl, gt_database直接按照现有代码生成即可。

谢谢您的解答，请问对“10%的训练集中的每个场景只保留一个实例”是在代码中的哪里体现的呢？因为我对比HSSDA工程，发现两个项目中的kitti_dataset.py文件都比较相似（应该是体现在这里？）。此外如果标注代价是1%，那就是5%*20%吗？如果是这样的话这5%的数据该如何选取呢？是在现有的10%（372 samples）随机选取一半数据就可以吗，还是有严格的选取机制呢？

**Comment by xmuqimingxia** [comment]
HINTED的代码中没有这部分的内容。我们是直接使用了之前的工作中（CoIn：https://github.com/xmuqimingxia/CoIn ） 使用的kitti_infos_train.pkl，这里的使用的pkl文件已经对数据进行了处理。如果您需要进行只保留一个实例的操作，则只需要修改kitti_dataset.py中的get_info 函数即可。

另外，在稀疏设置中，如果是标注代价1%，则只需要随机保留5%的标注帧，每一帧标注一个实例即可。我们进行过多组实验，随机的选择对车辆精度影响不大。为了平衡多类别的精度，您可以优先选择保留行人，和自行车的注释。

**Comment by xiao1512** [comment]
您好，我该如何优先保留行人和自行车呢？求解答
